### ISSUE TITLE
NoSuchMethodError on Intellij IDEA 2017.3

### ISSUE THREAD

**Issue by DukeKan** [cuba-labs/cuba-events-intellij-plugin#2]
TC 1:
Push on the icon near to the events.publish() method 

```
com.intellij.usages.UsageViewSettings.setGroupByFileStructure(Z)V
java.lang.NoSuchMethodError: com.intellij.usages.UsageViewSettings.setGroupByFileStructure(Z)V
	at com.haulmont.intellij.cubaevents.usages.ShowUsagesAction.<init>(ShowUsagesAction.java:140)
	at com.haulmont.intellij.cubaevents.CubaEventsLineMarkerProvider.showEventReceivers(CubaEventsLineMarkerProvider.java:141)
	at com.intellij.codeInsight.daemon.NavigateAction.actionPerformed(NavigateAction.java:56)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.openapi.editor.impl.EditorGutterComponentImpl.performAction(EditorGutterComponentImpl.java:1658)
	at com.intellij.openapi.editor.impl.EditorGutterComponentImpl.mouseReleased(EditorGutterComponentImpl.java:1619)
```

TC 2:
Icon near to the class definition
```
java.lang.NoSuchMethodError: com.intellij.usages.UsageViewSettings.setGroupByFileStructure(Z)V
	at com.haulmont.intellij.cubaevents.usages.ShowUsagesAction.<init>(ShowUsagesAction.java:140)
	at com.haulmont.intellij.cubaevents.CubaEventsLineMarkerProvider.showEventUsages(CubaEventsLineMarkerProvider.java:71)
	at com.intellij.codeInsight.daemon.NavigateAction.actionPerformed(NavigateAction.java:56)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.openapi.editor.impl.EditorGutterComponentImpl.performAction(EditorGutterComponentImpl.java:1658)
	at com.intellij.openapi.editor.impl.EditorGutterComponentImpl.mouseReleased(EditorGutterComponentImpl.java:1619)
```

**Comment by jreznot** [comment]
The 0.2+ plugin is compatible with IntelliJ 2018.1 + only
