### ISSUE TITLE
NoSuchMethodError with IDEA 2018.1.2

### ISSUE THREAD

**Issue by jreznot** [cuba-labs/cuba-events-intellij-plugin#3]
```
com.intellij.psi.PsiMethod.getAnnotation(Ljava/lang/String;)Lcom/intellij/psi/PsiAnnotation;
java.lang.NoSuchMethodError: com.intellij.psi.PsiMethod.getAnnotation(Ljava/lang/String;)Lcom/intellij/psi/PsiAnnotation;
	at com.haulmont.intellij.cubaevents.CubaEventsLineMarkerProvider.showEventSenders(CubaEventsLineMarkerProvider.java:104)
	at com.intellij.codeInsight.daemon.NavigateAction.actionPerformed(NavigateAction.java:56)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
```

IntelliJ IDEA 2018.1.2 (Community Edition)
Build #IC-181.4668.68, built on April 24, 2018
JRE: 1.8.0_152-release-1136-b29 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

**Comment by neugaojin** [comment]
i get the same problem,
my gradle version is com.android.tools.build:gradle:3.0.1
Migrate to Android Plugin for Gradle 3.1.0 solved
